-- MySQL Script generated by MySQL Workbench
-- Thu Jul 18 14:50:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

CREATE TABLE IF NOT EXISTS `mydb`.`InfoCliente` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Idade` INT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transacao` (
  `idTransacao` INT NOT NULL AUTO_INCREMENT,
  `Saldo` DOUBLE NOT NULL,
  `limite` DOUBLE NULL,
  PRIMARY KEY (`idTransacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `InfoCliente_CPF` INT NOT NULL,
  `Transacao_idTransacao` INT NOT NULL,
  `Apelido` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`, `Transacao_idTransacao`),
    FOREIGN KEY (`InfoCliente_CPF`)
    REFERENCES `mydb`.`InfoCliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Transacao1`	
    FOREIGN KEY (`Transacao_idTransacao`)
    REFERENCES `mydb`.`Transacao` (`idTransacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


